// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:larm/src/data/models/alarm.dart';
import 'package:larm/src/data/models/larm_timer.dart';
import 'package:larm/src/data/models/settings.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AlarmAdapter());
    registerAdapter(LarmTimerAdapter());
    registerAdapter(SettingsAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AlarmAdapter());
    registerAdapter(LarmTimerAdapter());
    registerAdapter(SettingsAdapter());
  }
}
